site_name: algorithms
site_description: My algorithm templates.
site_author: James Amcones
site_url: https://amcones.cn/algorithms
theme:
  name: material
  language: 'zh'
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.footer
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.share
# Repository
repo_name: 'amcones/algorithms'
repo_url: 'https://github.com/amcones/algorithms'
edit_uri: edit/main/docs/

# Copyright
copyright: '<a href="https://github.com/amcones/algorithms">algorithms</a> © 2025 by <a href="https://amcones.cn">James Amcones</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;">'

plugins:
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: datetime
      enable_creation_date: true
  - tags
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true

markdown_extensions:
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - toc
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist
  - pymdownx.progressbar

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
